/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdminstrativeRole;

import Business.CVSAdministrator;
import Business.Drug;
import Business.Manufacturer;
import Business.ManufacturerDirectory;
import Business.Store;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ankit Bhayani
 */
public class SearchStoresInventoryJPanel extends javax.swing.JPanel {

    
    private JPanel userProcessContainer;
    private CVSAdministrator cVSAdministrator;
    /**
     * Creates new form SearchStoresInventoryJPanel
     */
    public SearchStoresInventoryJPanel(JPanel upc, CVSAdministrator cVSAdministrator) {
        initComponents();
        userProcessContainer = upc;
        this.cVSAdministrator=cVSAdministrator;
        refreshTable();
        status.setText("Please select one of the store to view the drugs");
        
    }

        public void refreshTable(){
        int rowCount = tblStoreList.getRowCount();
        DefaultTableModel model = (DefaultTableModel) tblStoreList.getModel();
        for(int i=rowCount-1;i>=0;i--){
            model.removeRow(i);
        }
        for (Store s : cVSAdministrator.storeDirectory.getStoreList()) {
            Object row[] = new Object[1];
            row[0] = s;
            model.addRow(row);
        }
    }
        
  

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblStoreList = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDrugAvailable = new javax.swing.JTable();
        Logo = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        status = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        tblStoreList.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tblStoreList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Store Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblStoreList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStoreListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStoreList);

        tblDrugAvailable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblDrugAvailable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug Name", "Drug Price", "Availability", "IsBelowThreshold"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblDrugAvailable);

        Logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ankit Bhayani\\Desktop\\logo.gif")); // NOI18N
        Logo.setText("jLabel2");

        btnBack.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnBack.setText("<<BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        status.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        status.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(btnBack))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(status)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(status)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnBack)
                .addContainerGap(99, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblStoreListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStoreListMouseClicked

        status.setText("");
        int selectedRow = tblStoreList.getSelectedRow();
        //Manufacturer manufacturer = (Manufacturer)tblStoreList.getValueAt(selectedRow, 0);
        Store store= (Store)tblStoreList.getValueAt(selectedRow, 0);
        //populateDrugTable(manufacturer);
         int rowCount = tblDrugAvailable.getRowCount();
        DefaultTableModel dtm = (DefaultTableModel) tblDrugAvailable.getModel();
        for(int i=rowCount-1;i>=0;i--){
            dtm.removeRow(i);
        }

        for(Drug drug : store.storeDrugCatalog.getDrugList()){
            Object row[] = new Object[4];
            row[0]=drug;
            row[1]=drug.getDrugPrice();
            row[2]=drug.getStock();
            row[3]=drug.isBelowThreshold();

            dtm.addRow(row);
        }

    }//GEN-LAST:event_tblStoreListMouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        backAction();
    }//GEN-LAST:event_btnBackActionPerformed

        private void backAction(){
        userProcessContainer.remove(this);
        /*Component [] componentArray = userProcessContainer.getComponents();
        Component c = componentArray[componentArray.length-1];
        ManageManufacturers ms = (ManageManufacturers) c;
        ms.refreshTable();*/
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel status;
    private javax.swing.JTable tblDrugAvailable;
    private javax.swing.JTable tblStoreList;
    // End of variables declaration//GEN-END:variables
}
