/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.PatientDirectory;
import Business.Person;
import Business.PersonDirectory;
import java.awt.CardLayout;
import java.awt.HeadlessException;
import java.sql.Timestamp;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Swati
 */
public class CreatePersonJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private PersonDirectory personDirectory;
    private PatientDirectory patientDirectory;
    /**
     * Creates new form CreateAccountJPanel
     */
    public CreatePersonJPanel(JPanel upc, PersonDirectory pd, PatientDirectory ptd) {
        initComponents();
       this.userProcessContainer = upc;
       this.personDirectory = pd;
       this.patientDirectory=ptd;
       //btnAddPatientDetails.setEnabled(false);
       /*
       if(txtAge.getText().length()>0){
            userProcessContainer.remove(this);
            CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
            cardLayout.previous(userProcessContainer);
        }*/           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtpersonName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtstreetAdress = new javax.swing.JTextField();
        txttown = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txtzipCode = new javax.swing.JTextField();
        txtoccupation = new javax.swing.JTextField();
        txtmobileNumber = new javax.swing.JTextField();
        txtemailAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblPatientStatus = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel1.setText("Create Person");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Person Name");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Street Address");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("Age");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("Town");

        txtpersonName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtpersonName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpersonNameActionPerformed(evt);
            }
        });
        txtpersonName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpersonNameKeyTyped(evt);
            }
        });

        txtAge.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAgeKeyTyped(evt);
            }
        });

        txtstreetAdress.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtstreetAdress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstreetAdressActionPerformed(evt);
            }
        });

        txttown.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txttown.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttownKeyTyped(evt);
            }
        });

        btnCreate.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnCreate.setText("Create Person");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txtzipCode.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtzipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtzipCodeActionPerformed(evt);
            }
        });
        txtzipCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtzipCodeKeyTyped(evt);
            }
        });

        txtoccupation.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtoccupation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtoccupationActionPerformed(evt);
            }
        });
        txtoccupation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtoccupationKeyTyped(evt);
            }
        });

        txtmobileNumber.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtmobileNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmobileNumberActionPerformed(evt);
            }
        });
        txtmobileNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmobileNumberKeyTyped(evt);
            }
        });

        txtemailAddress.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtemailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailAddressActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setText("Mobile Number");

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setText("Email Address");

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel8.setText("Occupation");

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel9.setText("Zip Code");

        lblPatientStatus.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        lblPatientStatus.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtpersonName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAge, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtstreetAdress, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttown, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(43, 43, 43))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(35, 35, 35)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtoccupation)
                            .addComponent(txtemailAddress, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmobileNumber, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtzipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(btnCreate))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnBack)))
                .addContainerGap(137, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(211, 211, 211)
                    .addComponent(lblPatientStatus)
                    .addContainerGap(377, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtpersonName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtstreetAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtzipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtoccupation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtemailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtmobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33)
                .addComponent(btnCreate)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(60, 60, 60)
                    .addComponent(lblPatientStatus)
                    .addContainerGap(380, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtstreetAdressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstreetAdressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstreetAdressActionPerformed

    private void txtpersonNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpersonNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpersonNameActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed

        lblPatientStatus.setText("");
        
        
     if(!(txtAge.getText().isEmpty() || txtAge.getText().contains(" ") ||
          txtzipCode.getText().isEmpty() || txtzipCode.getText().contains(" ") ||
          txtoccupation.getText().isEmpty() || txtoccupation.getText().contains(" ") ||
          txtemailAddress.getText().isEmpty() || txtemailAddress.getText().contains(" ") ||
          txttown.getText().isEmpty() || txttown.getText().contains(" ") ||
          txtmobileNumber.getText().isEmpty() || txtmobileNumber.getText().contains(" ") ||
          txtpersonName.getText().isEmpty() || 
          txtstreetAdress.getText().isEmpty())){  
        
            try {
                String pName = txtpersonName.getText();
                String town = txttown.getText();
                String padd = txtstreetAdress.getText();
                String email = txtemailAddress.getText();
                String occup = txtoccupation.getText();
                int zipCode =  Integer.valueOf(txtzipCode.getText());
                int pAge = Integer.valueOf(txtAge.getText());
                int cellno = Integer.valueOf(txtmobileNumber.getText());


                Person person = personDirectory.addPerson();
                person.CounterAddPerson();

                person.setPersonName(pName);
                person.setAge(pAge);
                person.setTown(town);
                person.setStreetAdress(padd);
                person.setAddedOn(String.valueOf(new Timestamp(System.currentTimeMillis())));
                person.setEmailAddress(email);
                person.setMobileNumber(cellno);
                person.setOccupation(occup);
                person.setZipCode(zipCode);

                //JOptionPane.showMessageDialog(null, "Successfully Created", "Information Message", JOptionPane.INFORMATION_MESSAGE);

                int dialogButton= JOptionPane.YES_NO_OPTION;
                int dialogResult= JOptionPane.showConfirmDialog(null, "Successfully Created! Do you want to add Patient Details/Vital Signs?", "Question", dialogButton);

                btnCreate.setEnabled(false);
                txtpersonName.setEnabled(false);
                lblPatientStatus.setText("Vital Signs added for this User, please go back to Manage section to view the details!");
                
                
                
                if (dialogResult==JOptionPane.YES_OPTION){
                    //btnAddPatientDetails.setEnabled(true);
                    CreatePatientJPanel createPatientJPanel = new CreatePatientJPanel(userProcessContainer, person, patientDirectory, personDirectory);
                    userProcessContainer.add("CreatePatientJPanel",createPatientJPanel);
                    CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
                    cardLayout.next(userProcessContainer);

                }
                else {
                            userProcessContainer.remove(this);
                            CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
                            cardLayout.previous(userProcessContainer);
                }          
            } catch (NumberFormatException numberFormatException) {
            JOptionPane.showMessageDialog(null, "Wrong Input Form", "Error Message", JOptionPane.ERROR_MESSAGE);} 
            
        }
        else{
            //JOptionPane.showMessageDialog(null, "Spaces or Null");
            lblPatientStatus.setText("Spaces or Null in the one of the Input fields!");
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtzipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtzipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtzipCodeActionPerformed

    private void txtoccupationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtoccupationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtoccupationActionPerformed

    private void txtmobileNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmobileNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmobileNumberActionPerformed

    private void txtemailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailAddressActionPerformed

    private void txtpersonNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpersonNameKeyTyped
        numberCheck(evt);
    }//GEN-LAST:event_txtpersonNameKeyTyped

    private void txtzipCodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtzipCodeKeyTyped
        characterCheck(evt);
    }//GEN-LAST:event_txtzipCodeKeyTyped

    private void txtAgeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyTyped
        characterCheck(evt);
    }//GEN-LAST:event_txtAgeKeyTyped

    private void txtoccupationKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtoccupationKeyTyped
        numberCheck(evt);
    }//GEN-LAST:event_txtoccupationKeyTyped

    private void txtmobileNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmobileNumberKeyTyped
        characterCheck(evt);
    }//GEN-LAST:event_txtmobileNumberKeyTyped

    private void txttownKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttownKeyTyped
        numberCheck(evt);
    }//GEN-LAST:event_txttownKeyTyped

    public void resetFields(){
    }
    
    
    public void numberCheck(java.awt.event.KeyEvent e){
         char ch = e.getKeyChar();
            if (Character.isDigit(ch) && ch!=8 && ch!=46){
                lblPatientStatus.setText("Please enter characters only!");
                e.consume();
            }
            else
                lblPatientStatus.setText("");
                
        
    }
    
    public void characterCheck(java.awt.event.KeyEvent e){
         char ch = e.getKeyChar();
            if (!Character.isDigit(ch) && ch!=8 && ch!=46){
                lblPatientStatus.setText("Please enter Numbers only!");
                e.consume();
            }
            else{
                lblPatientStatus.setText("");
                //lblVitalSignStatus.setText("");
            }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblPatientStatus;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtemailAddress;
    private javax.swing.JTextField txtmobileNumber;
    private javax.swing.JTextField txtoccupation;
    private javax.swing.JTextField txtpersonName;
    private javax.swing.JTextField txtstreetAdress;
    private javax.swing.JTextField txttown;
    private javax.swing.JTextField txtzipCode;
    // End of variables declaration//GEN-END:variables
}
