/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Patient;
import Business.PatientDirectory;
import Business.PersonDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Swati
 */
public class ManagePersonWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private PersonDirectory personDirectory;
    private PatientDirectory patientDirectory;        
    /**
     * Creates new form ManageAccountWorkAreaJPanel
     */
    public ManagePersonWorkAreaJPanel(JPanel upc, PersonDirectory pd, PatientDirectory ptd) {
       initComponents();
       this.userProcessContainer = upc;
       this.personDirectory = pd;
       this.patientDirectory=ptd;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreatePersonPatient = new javax.swing.JButton();
        btnManagePersonPatient = new javax.swing.JButton();

        btnCreatePersonPatient.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnCreatePersonPatient.setText("Create Person/Patient");
        btnCreatePersonPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePersonPatientActionPerformed(evt);
            }
        });

        btnManagePersonPatient.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnManagePersonPatient.setText("Manage");
        btnManagePersonPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePersonPatientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnManagePersonPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreatePersonPatient))
                .addContainerGap(318, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(btnCreatePersonPatient)
                .addGap(28, 28, 28)
                .addComponent(btnManagePersonPatient)
                .addContainerGap(299, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreatePersonPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePersonPatientActionPerformed
        CreatePersonJPanel createAccountJPanel = new CreatePersonJPanel(userProcessContainer,personDirectory,patientDirectory);
        userProcessContainer.add("CreateAccountJPanel",createAccountJPanel);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnCreatePersonPatientActionPerformed

    private void btnManagePersonPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePersonPatientActionPerformed
        
        /*for(Patient p:patientDirectory.getPatientList()){
        JOptionPane.showMessageDialog(null, p.getPatientId());}
        */
        
        ManagePersonPatientJPanel manageAccountJPanel = new ManagePersonPatientJPanel(userProcessContainer,personDirectory,patientDirectory);
        userProcessContainer.add("ManageAccountJPanel",manageAccountJPanel);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
       
    }//GEN-LAST:event_btnManagePersonPatientActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreatePersonPatient;
    private javax.swing.JButton btnManagePersonPatient;
    // End of variables declaration//GEN-END:variables
}
