/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Admin;

import Business.Logic.Business;
import Business.Logic.SalesPersonDirectory;
import Business.Logic.UserAccountDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Ankit Bhayani
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Business business;
    private SalesPersonDirectory employeeDirectory;
    private UserAccountDirectory userAccountDirectory;
            
    
    /**
     * Creates new form AdminWorkAreaJPanel
     */
    public AdminWorkAreaJPanel(JPanel userProcessContainer,Business business) {
        initComponents();
        this.business=business;
        this.userProcessContainer=userProcessContainer;
        employeeDirectory=business.getEmployeeDirectory();
        userAccountDirectory= business.getUserDirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageEmployee = new javax.swing.JButton();
        btnManageUserAccounts = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnBusinessAnalytics = new javax.swing.JButton();

        btnManageEmployee.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnManageEmployee.setText("Manage Employee");
        btnManageEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEmployeeActionPerformed(evt);
            }
        });

        btnManageUserAccounts.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnManageUserAccounts.setText("Manage UserAccounts");
        btnManageUserAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageUserAccountsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel1.setText("Admin Work Area");

        btnBusinessAnalytics.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnBusinessAnalytics.setText("View Business Analytics");
        btnBusinessAnalytics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusinessAnalyticsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnManageUserAccounts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnManageEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBusinessAnalytics, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jLabel1)))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(83, 83, 83)
                .addComponent(btnManageEmployee)
                .addGap(40, 40, 40)
                .addComponent(btnManageUserAccounts)
                .addGap(37, 37, 37)
                .addComponent(btnBusinessAnalytics)
                .addContainerGap(154, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEmployeeActionPerformed
        ManageEmployeeJPanel manageEmployeeJPanel = new ManageEmployeeJPanel(userProcessContainer,business);
        userProcessContainer.add("ManageEmployeeJPanel",manageEmployeeJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageEmployeeActionPerformed

    private void btnManageUserAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageUserAccountsActionPerformed
        ManageUserAccountsJPanel manageUserAccountsJPanel = new ManageUserAccountsJPanel(userProcessContainer,business);
        userProcessContainer.add("ManageUserAccountsJPanel",manageUserAccountsJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageUserAccountsActionPerformed

    private void btnBusinessAnalyticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusinessAnalyticsActionPerformed
        ViewBusinessAnalytics vba = new ViewBusinessAnalytics(userProcessContainer, business);
        userProcessContainer.add("ViewBusinessAnalytics",vba);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
					
    }//GEN-LAST:event_btnBusinessAnalyticsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusinessAnalytics;
    private javax.swing.JButton btnManageEmployee;
    private javax.swing.JButton btnManageUserAccounts;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
