/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Admin;

import Business.Logic.Business;
import Business.Logic.SalesPerson;
import Business.Logic.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ankit Bhayani
 */
public class ManageUserAccountsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Business business;
    /**
     * Creates new form ManageUserAccountsJPanel
     */
    public ManageUserAccountsJPanel(JPanel userProcessContainer,Business business) {
        initComponents();
        this.business=business;
        this.userProcessContainer=userProcessContainer;
        refreshTable();
    }
    
     public void refreshTable(){
        /*int rowCount = supplierTable.getRowCount();
        for(int i=rowCount-1;i>=0;i--){
            model.removeRow(i);
        }*/
        
        DefaultTableModel model = (DefaultTableModel) tblUserAccount.getModel();
        
        model.setRowCount(0);
        for (UserAccount ua : business.getUserDirectory().getUserAccountList()) {
            Object row[] = new Object[3];
            row[0] = ua;
            row[1] = ua.getUserName();
            row[2] = ua.getRole();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRefreshUA = new javax.swing.JButton();
        btnAddUserAccount = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUserAccount = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnBackUA = new javax.swing.JButton();
        btnRemoveUA = new javax.swing.JButton();

        btnRefreshUA.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnRefreshUA.setText("Refresh");
        btnRefreshUA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshUAActionPerformed(evt);
            }
        });

        btnAddUserAccount.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnAddUserAccount.setText("Add User Account");
        btnAddUserAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserAccountActionPerformed(evt);
            }
        });

        tblUserAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Person", "User Name", "Role"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblUserAccount);
        if (tblUserAccount.getColumnModel().getColumnCount() > 0) {
            tblUserAccount.getColumnModel().getColumn(0).setResizable(false);
            tblUserAccount.getColumnModel().getColumn(1).setResizable(false);
            tblUserAccount.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel1.setText("Manage User Accounts");

        btnBackUA.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnBackUA.setText("<<Back");
        btnBackUA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackUAActionPerformed(evt);
            }
        });

        btnRemoveUA.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnRemoveUA.setText("Remove");
        btnRemoveUA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveUAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBackUA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRemoveUA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRefreshUA)
                                .addGap(18, 18, 18)
                                .addComponent(btnAddUserAccount))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddUserAccount)
                    .addComponent(btnRefreshUA)
                    .addComponent(btnBackUA)
                    .addComponent(btnRemoveUA))
                .addContainerGap(68, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackUAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackUAActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackUAActionPerformed

    private void btnRefreshUAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshUAActionPerformed
        refreshTable();
    }//GEN-LAST:event_btnRefreshUAActionPerformed

    private void btnRemoveUAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveUAActionPerformed
        int selectedRow = tblUserAccount.getSelectedRow();
        if(selectedRow>=0){
            int dialogResult=JOptionPane.showConfirmDialog(null, "Would you like to remove the selected UserAccount?","Warning",JOptionPane.YES_NO_OPTION);
                
            if(dialogResult== JOptionPane.YES_OPTION){
                    UserAccount ua  = (UserAccount)tblUserAccount.getValueAt(selectedRow, 0);
                
                
               
                    
        }
        else{
            
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
            
        }       
    }//GEN-LAST:event_btnRemoveUAActionPerformed

    private void btnAddUserAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserAccountActionPerformed
        
        CreateUserAccountJPanel cuajp = new CreateUserAccountJPanel(userProcessContainer,business,this);
        userProcessContainer.add("CreateUserAccountJPanel",cuajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAddUserAccountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUserAccount;
    private javax.swing.JButton btnBackUA;
    private javax.swing.JButton btnRefreshUA;
    private javax.swing.JButton btnRemoveUA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUserAccount;
    // End of variables declaration//GEN-END:variables
}
