/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DonorRole;

import Business.BloodDonation;
import Business.Employee.Donor;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.DonorOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ankit Bhayani
 */
public class DonorDetailsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Donor donor;
    private DonorOrganization donorOrganization;
    
    /**
     * Creates new form DonorDetailsJPanel
     */
    public DonorDetailsJPanel(JPanel pnl, UserAccount ua, Organization o) {
        initComponents();
        this.userProcessContainer = pnl;
        this.userAccount = ua;
        this.donorOrganization = (DonorOrganization)o;
        
        
        
        for(Employee e: donorOrganization.getEmployeeDirectory().getEmployeeList()){
            if(e.getName().equals(ua.getEmployee().getName())){
                this.donor= (Donor)e;
            }
                
        }
        lblDonorName.setText(donor.getName());
        populateDonorDetails();
        
    }

    public void populateDonorDetails(){
        DefaultTableModel model = (DefaultTableModel)tblDonorDetails.getModel();
                
        model.setRowCount(0);
        
        //LabTestWorkRequest ltwruserAccount.getWorkQueue().getWorkRequestList();
        
            for(BloodDonation bd: donor.getBloodDonationList()){
                //JOptionPane.showMessageDialog(null, request1.getSender());
                //String abc = ((LabTestWorkRequest) request1).getTestResult();
                //Employee e = ((LabTestWorkRequest) request1).getDonor();
                //JOptionPane.showMessageDialog(null,e.getName());
                //JOptionPane.showMessageDialog(null,abc);
                
                
                Object[] row = new Object[4];
                row[0] = bd;
                row[1] = bd.getNurse();
                row[2] = bd.getQuantity();
                row[3] = bd.getBarCode();
                

            
            model.addRow(row);
            }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDonorDetails = new javax.swing.JTable();
        lblDonorName = new javax.swing.JLabel();

        tblDonorDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "DonationDate", "Nurse", "Quantity", "BarCode"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDonorDetails);

        lblDonorName.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(lblDonorName)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblDonorName)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDonorName;
    private javax.swing.JTable tblDonorDetails;
    // End of variables declaration//GEN-END:variables
}
