/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PatientRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.IndividualUser.Doctor;
import Business.IndividualUser.Patient;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.Organization.PatientOrganization;
import Business.UserAccount.UserAccount;
import Business.Utils.MyEmailVerifier;
import Business.Utils.MyIntegerVerifier;
import Business.Utils.MyPhoneNumberVerifier;
import Business.Utils.MyStringVerifier;
import Business.VitalSigns.VitalSign;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.HeadlessException;
import java.sql.Timestamp;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Swati
 */
public class PatientProfileAndOtherDetails extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Patient patient;
    private Doctor doc;
    private PatientOrganization patientOrganization;
    private Enterprise enterprise;
    private Enterprise docUAenterprise;
    private EcoSystem ecoSystem;
    private VitalSign vs;
    private DoctorOrganization doctorOrganization;
    private UserAccount docUA =null; 
    
    /**
     * Creates new form CreateAccountJPanel
     */
    public PatientProfileAndOtherDetails(JPanel pnl, UserAccount ua, Organization o, Enterprise e, EcoSystem es) {
        initComponents();
        this.userProcessContainer = pnl;
        this.userAccount = ua;
        this.patientOrganization = (PatientOrganization)o;
        this.enterprise = e;
        this.ecoSystem = es;
        this.patient= (Patient)ua.getEmployee();
        cmbMajorDisease.setEditable(false);
        txtpersonName.setText(patient.getName());
        txtAge.setText(String.valueOf(patient.getAge()));
        txtemailAddress.setText(patient.getEmailAddress());
        txtmobileNumber.setText(String.valueOf(patient.getMobileNumber()));
        txtoccupation.setText(patient.getOccupation());
        txtstreetAdress.setText(patient.getStreetAdress());
        txttown.setText(patient.getTown());
        txtzipCode.setText(String.valueOf(patient.getZipCode()));
        MyEmailVerifier myEmailVerifier = new MyEmailVerifier();
        MyStringVerifier myStringVerifier  = new MyStringVerifier();
        MyIntegerVerifier myIntegerVerifier = new MyIntegerVerifier();
        MyPhoneNumberVerifier myPhoneNumberVerifier = new MyPhoneNumberVerifier();
        txtemailAddress.setInputVerifier(myEmailVerifier);
        txtmobileNumber.setInputVerifier(myPhoneNumberVerifier);
        txtAge.setInputVerifier(myIntegerVerifier);
        txtoccupation.setInputVerifier(myStringVerifier);
        txtzipCode.setInputVerifier(myIntegerVerifier);
        txttown.setInputVerifier(myStringVerifier);
        popCombo();
        
    }

    
    public void popCombo(){
        if(patient.getPatientChronicDisease()!=null){
            if(patient.getPatientChronicDisease().equals("Diabetes"))
                cmbMajorDisease.setSelectedIndex(1);
            else if(patient.getPatientChronicDisease().equals("Cancer"))
                cmbMajorDisease.setSelectedIndex(2); 
            else if(patient.getPatientChronicDisease().equals("Arthiritis"))
                cmbMajorDisease.setSelectedIndex(3);
            else if(patient.getPatientChronicDisease().equals("Blood Pressure Abnormalities"))
                cmbMajorDisease.setSelectedIndex(4);
            else if(patient.getPatientChronicDisease().equals("Epilepsy"))
                cmbMajorDisease.setSelectedIndex(5);
            else if(patient.getPatientChronicDisease().equals("Thyroid disease"))
                cmbMajorDisease.setSelectedIndex(6);
            else if(patient.getPatientChronicDisease().equals("Hypertension"))
                cmbMajorDisease.setSelectedIndex(7);
            else if(patient.getPatientChronicDisease().equals("Chronic hepatitis"))
                cmbMajorDisease.setSelectedIndex(8);
            else if(patient.getPatientChronicDisease().equals("Others"))
                cmbMajorDisease.setSelectedIndex(9);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUpdate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblPatientStatus = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtstreetAdress = new javax.swing.JTextField();
        txttown = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtzipCode = new javax.swing.JTextField();
        txtemailAddress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtpersonName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtoccupation = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtmobileNumber = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblSystolicBloodPressure1 = new javax.swing.JLabel();
        cmbMajorDisease = new javax.swing.JComboBox();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUpdate.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/PatientRole/updateButton.png"))); // NOI18N
        btnUpdate.setText("Update Profile");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, -1, 30));

        btnBack.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/PatientRole/backButton.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));

        lblPatientStatus.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        lblPatientStatus.setForeground(new java.awt.Color(204, 0, 0));
        add(lblPatientStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 60, -1, -1));

        jLabel10.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel10.setText("Patient's Profile and Account Information Panel");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 19, -1, -1));

        txtstreetAdress.setEditable(false);
        txtstreetAdress.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        txttown.setEditable(false);
        txttown.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txttown.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttownKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Home Address");

        txtzipCode.setEditable(false);
        txtzipCode.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtzipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtzipCodeActionPerformed(evt);
            }
        });
        txtzipCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtzipCodeKeyTyped(evt);
            }
        });

        txtemailAddress.setEditable(false);
        txtemailAddress.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtemailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailAddressActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel9.setText("Zip Code");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("City");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("Age");

        txtAge.setEditable(false);
        txtAge.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAgeKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Patient Name");

        txtpersonName.setEditable(false);
        txtpersonName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtpersonName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpersonNameActionPerformed(evt);
            }
        });
        txtpersonName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpersonNameKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel8.setText("Occupation");

        txtoccupation.setEditable(false);
        txtoccupation.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtoccupation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtoccupationActionPerformed(evt);
            }
        });
        txtoccupation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtoccupationKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setText("Email Address");

        txtmobileNumber.setEditable(false);
        txtmobileNumber.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtmobileNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmobileNumberActionPerformed(evt);
            }
        });
        txtmobileNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmobileNumberKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setText("Mobile Number");

        lblSystolicBloodPressure1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblSystolicBloodPressure1.setText("Chronic Disease");

        cmbMajorDisease.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cmbMajorDisease.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "(Select One)", "Diabetes", "Cancer", "Arthiritis", "Blood Pressure Abnormalities", "Epilepsy", "Thyroid disease", "Hypertension", "Chronic hepatitis", "Others" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(84, 84, 84)
                                .addComponent(txtAge))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblSystolicBloodPressure1)
                                .addGap(18, 18, 18)
                                .addComponent(cmbMajorDisease, 0, 1, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel5))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txttown, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtzipCode))))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtmobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtstreetAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtoccupation, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtemailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtpersonName, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtpersonName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSystolicBloodPressure1)
                            .addComponent(cmbMajorDisease, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtzipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txttown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtstreetAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtoccupation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtemailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtmobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 650, 270));

        btnSave.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/PatientRole/saveButton.png"))); // NOI18N
        btnSave.setText("SAVE");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 100, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void txtpersonNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpersonNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpersonNameActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        //cmbMajorDisease.setEditable(true);
        txtAge.setEditable(true);
        txtemailAddress.setEditable(true);
        txtmobileNumber.setEditable(true);
        txtoccupation.setEditable(true);
        txtstreetAdress.setEditable(true);
        txttown.setEditable(true);
        txtzipCode.setEditable(true);
        btnSave.setEnabled(true);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        PatientWorkAreaJPanel pwajp = (PatientWorkAreaJPanel) component;
        pwajp.profileUpdate();
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtzipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtzipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtzipCodeActionPerformed

    private void txtoccupationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtoccupationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtoccupationActionPerformed

    private void txtmobileNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmobileNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmobileNumberActionPerformed

    private void txtemailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailAddressActionPerformed

    private void txtpersonNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpersonNameKeyTyped
        numberCheck(evt);
    }//GEN-LAST:event_txtpersonNameKeyTyped

    private void txtzipCodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtzipCodeKeyTyped
        characterCheck(evt);
    }//GEN-LAST:event_txtzipCodeKeyTyped

    private void txtAgeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyTyped
        characterCheck(evt);
    }//GEN-LAST:event_txtAgeKeyTyped

    private void txtoccupationKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtoccupationKeyTyped
        numberCheck(evt);
    }//GEN-LAST:event_txtoccupationKeyTyped

    private void txtmobileNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmobileNumberKeyTyped
        characterCheck(evt);
    }//GEN-LAST:event_txtmobileNumberKeyTyped

    private void txttownKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttownKeyTyped
        numberCheck(evt);
    }//GEN-LAST:event_txttownKeyTyped

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        
      if(cmbMajorDisease.getSelectedIndex()==0){
          JOptionPane.showMessageDialog(null, "Please select a disease");
          return;
      }
      
        
      lblPatientStatus.setText("");
      if(!(txtAge.getText().trim().length()==0 || txtAge.getText().contains(" ") ||
          txtzipCode.getText().trim().length()==0 || txtzipCode.getText().contains(" ") ||
          txtoccupation.getText().trim().length()==0 ||
          txtemailAddress.getText().trim().length()==0 || txtemailAddress.getText().contains(" ") ||
          txttown.getText().trim().length()==0 ||
          txtmobileNumber.getText().trim().length()==0 ||
          txtpersonName.getText().trim().length()==0 || 
          txtstreetAdress.getText().trim().length()==0)){  

            if(txtmobileNumber.getText().equals("0") ||
               txtAge.getText().equals("0") ||
               txtzipCode.getText().equals("0")     ){
                JOptionPane.showMessageDialog(null, "Zero is not a legal value");
                return;
            }
           try {
                //String pName = txtpersonName.getText();
                String town = txttown.getText();
                String padd = txtstreetAdress.getText();
                String email = txtemailAddress.getText();
                String occup = txtoccupation.getText();
                int zipCode =  Integer.valueOf(txtzipCode.getText());
                int pAge = Integer.valueOf(txtAge.getText());
                long cellno = Long.valueOf(txtmobileNumber.getText());

                //patient = personDirectory.addPerson();
                //patient.CounterAddPerson();
                //JOptionPane.showMessageDialog(null, cellno + 1);
                //patient.setPersonName(pName);
                if(txtzipCode.getText().trim().length()!=5){
                    JOptionPane.showMessageDialog(null, "ZIP code should be5 digits");
                    return;
                }
                
                patient.setAge(pAge);
                patient.setTown(town);
                patient.setStreetAdress(padd);
                //patient.setAddedOn(String.valueOf(new Timestamp(System.currentTimeMillis())));
                patient.setEmailAddress(email);
                patient.setMobileNumber(cellno);
                patient.setOccupation(occup);
                patient.setZipCode(zipCode);
                patient.setPatientChronicDisease((String) cmbMajorDisease.getSelectedItem());

                //JOptionPane.showMessageDialog(null, "Successfully Created", "Information Message", JOptionPane.INFORMATION_MESSAGE);
                                                                                                                               
                /*int dialogButton= JOptionPane.YES_NO_OPTION;
                int dialogResult= JOptionPane.showConfirmDialog(null, "Successfully Created! Do you want to add Patient Details/Vital Signs?", "Question", dialogButton);

                btnCreate.setEnabled(false);
                txtpersonName.setEnabled(false);
                lblPatientStatus.setText("Vital Signs added for this User, please go back to Manage section to view the details!");
                */
                JOptionPane.showMessageDialog(null, "Profile updated successfully!!");
                btnSave.setEnabled(false);
                txtAge.setEditable(false);
                txtemailAddress.setEditable(false);
                txtmobileNumber.setEditable(false);
                txtoccupation.setEditable(false);
                txtstreetAdress.setEditable(false);
                txttown.setEditable(false);
                txtzipCode.setEditable(false);
                
            } catch (NumberFormatException numberFormatException) {
               JOptionPane.showMessageDialog(null, numberFormatException, "Error Message", JOptionPane.ERROR_MESSAGE);
            }
            
        }
        else{
            //JOptionPane.showMessageDialog(null, "Spaces or Null");
            lblPatientStatus.setText("Spaces or Null in the one of the Input fields!");
        }
        
        
        
    }//GEN-LAST:event_btnSaveActionPerformed

    public void resetFields(){
    }
    
    
    public void numberCheck(java.awt.event.KeyEvent e){
         char ch = e.getKeyChar();
            if (Character.isDigit(ch) && ch!=8 && ch!=46){
                lblPatientStatus.setText("Please enter characters only!");
                e.consume();
            }
            else
                lblPatientStatus.setText("");
                
        
    }
    
    public void characterCheck(java.awt.event.KeyEvent e){
         char ch = e.getKeyChar();
            if (!Character.isDigit(ch) && ch!=8 && ch!=46){
                lblPatientStatus.setText("Please enter Numbers only!");
                e.consume();
            }
            else{
                lblPatientStatus.setText("");
                //lblVitalSignStatus.setText("");
            }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox cmbMajorDisease;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPatientStatus;
    private javax.swing.JLabel lblSystolicBloodPressure1;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtemailAddress;
    private javax.swing.JTextField txtmobileNumber;
    private javax.swing.JTextField txtoccupation;
    private javax.swing.JTextField txtpersonName;
    private javax.swing.JTextField txtstreetAdress;
    private javax.swing.JTextField txttown;
    private javax.swing.JTextField txtzipCode;
    // End of variables declaration//GEN-END:variables
}
