/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Person;
import javax.swing.JOptionPane;

/**
 *
 * @author Swati
 */
public class CreatePersonJPanel extends javax.swing.JPanel {

    
    private Person person;
    /**
     * Creates new form CreatePersonJPanel
     */
    public CreatePersonJPanel(Person p) {
        initComponents();
        this.person=p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCreateProfile = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        Seperator = new javax.swing.JSeparator();
        lblLastName = new javax.swing.JLabel();
        lblMiddleName = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lbldateOfBirth = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblStreetAddress = new javax.swing.JLabel();
        lblZipCode = new javax.swing.JLabel();
        lblTown = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtMiddleName = new javax.swing.JTextField();
        txtDateOfBirth = new javax.swing.JTextField();
        txtStreetAddress = new javax.swing.JTextField();
        txtTown = new javax.swing.JTextField();
        lblOccupation = new javax.swing.JLabel();
        lblEmailAddress = new javax.swing.JLabel();
        lblContactDetails = new javax.swing.JLabel();
        lblAreaCode = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        txtOccupation = new javax.swing.JTextField();
        txtEmailAddress = new javax.swing.JTextField();
        txtAreaCode = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        comboGender = new javax.swing.JComboBox();
        txtZipCode = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();

        lblCreateProfile.setFont(new java.awt.Font("Cambria", 3, 14)); // NOI18N
        lblCreateProfile.setText("Profile Creation");

        lblFirstName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblFirstName.setText("First Name");

        lblLastName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblLastName.setText("Last Name");

        lblMiddleName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblMiddleName.setText("Middle Name");

        lblName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblName.setText("Name");

        lbldateOfBirth.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lbldateOfBirth.setText("Date Of Birth (in YYYY/MM/DD)");

        lblGender.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblGender.setText("Gender");

        lblStreetAddress.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblStreetAddress.setText("Street Address");

        lblZipCode.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblZipCode.setText("ZipCode");

        lblTown.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblTown.setText("Town");

        txtFirstName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFirstNameKeyTyped(evt);
            }
        });

        txtLastName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        txtMiddleName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtMiddleName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMiddleNameActionPerformed(evt);
            }
        });

        txtDateOfBirth.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        txtStreetAddress.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        txtTown.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        lblOccupation.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblOccupation.setText("Occupation");

        lblEmailAddress.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblEmailAddress.setText("Email Address");

        lblContactDetails.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblContactDetails.setText("Contact Details");

        lblAreaCode.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblAreaCode.setText("Area Code");

        lblPhoneNumber.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblPhoneNumber.setText("Phone Number");

        txtOccupation.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        txtEmailAddress.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        txtAreaCode.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        txtPhoneNumber.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        comboGender.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        comboGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        txtZipCode.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        btnCreate.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblContactDetails)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblStreetAddress)
                                            .addComponent(lblOccupation))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblEmailAddress)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTown)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTown, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblZipCode)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lbldateOfBirth)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblGender)
                                .addGap(18, 18, 18)
                                .addComponent(comboGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblName)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblFirstName)
                                        .addGap(29, 29, 29))
                                    .addComponent(txtFirstName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLastName)
                                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMiddleName)
                                    .addComponent(txtMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Seperator))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCreate)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtAreaCode, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblAreaCode)))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPhoneNumber)
                            .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(lblCreateProfile)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lblCreateProfile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Seperator, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblName)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblLastName)
                                    .addComponent(lblMiddleName))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFirstName)
                        .addGap(15, 15, 15)
                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldateOfBirth)
                    .addComponent(lblGender)
                    .addComponent(txtDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStreetAddress)
                    .addComponent(lblTown)
                    .addComponent(lblZipCode)
                    .addComponent(txtStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOccupation)
                    .addComponent(lblEmailAddress)
                    .addComponent(txtOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneNumber)
                    .addComponent(lblAreaCode))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContactDetails)
                    .addComponent(txtAreaCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnCreate)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMiddleNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMiddleNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMiddleNameActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        
        if(txtFirstName.getText().isEmpty() || txtLastName.getText().isEmpty() || txtMiddleName.getText().isEmpty() ||
           txtDateOfBirth.getText().isEmpty() || txtStreetAddress.getText().isEmpty() || txtTown.getText().isEmpty() ||
           txtZipCode.getText().isEmpty() || txtOccupation.getText().isEmpty() || txtEmailAddress.getText().isEmpty() ||
           txtAreaCode.getText().isEmpty() || txtPhoneNumber.getText().isEmpty() )
        {
            JOptionPane.showMessageDialog(null, "One of the fields is empty, please complete all the details!!");
        }
        else{
            person.setFirstName(txtFirstName.getText());
            person.setLastName(txtLastName.getText());
            person.setMiddleName(txtMiddleName.getText());
            person.setDateOfBirth(txtDateOfBirth.getText());
            person.setStreetAdress(txtStreetAddress.getText());
            person.setTown(txtTown.getText());
            person.setZipCode(txtZipCode.getText());
            person.setOccupation(txtOccupation.getText());
            person.setEmailAddress(txtEmailAddress.getText());
            person.setAreaCodeForPhone(txtAreaCode.getText());
            person.setPhoneNumber(txtPhoneNumber.getText());

            JOptionPane.showMessageDialog(null, "Profile created successfully");
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void txtFirstNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstNameKeyTyped
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
           
        if(!(ch >= '0' && ch <= '9'))
        {}
        else
            JOptionPane.showMessageDialog(null, "Numbwer");
                                      
    }//GEN-LAST:event_txtFirstNameKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator Seperator;
    private javax.swing.JButton btnCreate;
    private javax.swing.JComboBox comboGender;
    private javax.swing.JLabel lblAreaCode;
    private javax.swing.JLabel lblContactDetails;
    private javax.swing.JLabel lblCreateProfile;
    private javax.swing.JLabel lblEmailAddress;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblMiddleName;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOccupation;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblStreetAddress;
    private javax.swing.JLabel lblTown;
    private javax.swing.JLabel lblZipCode;
    private javax.swing.JLabel lbldateOfBirth;
    private javax.swing.JTextField txtAreaCode;
    private javax.swing.JTextField txtDateOfBirth;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMiddleName;
    private javax.swing.JTextField txtOccupation;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtStreetAddress;
    private javax.swing.JTextField txtTown;
    private javax.swing.JTextField txtZipCode;
    // End of variables declaration//GEN-END:variables
}
