/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Patient;
import Business.VitalSign;
import java.sql.Timestamp;
import javax.swing.JOptionPane;


public class CreateJPanel extends javax.swing.JPanel {

     
    private Patient patient;
    
    public CreateJPanel(Patient p) {
        initComponents();
        this.patient=p;
        
        txtHeartRate.setEnabled(false);
        txtSystolicBloodPressure.setEnabled(false);
        txtRespiratoryRate.setEnabled(false);
        txtWeight.setEnabled(false);
        btnCreateVitalSign.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCreate = new javax.swing.JLabel();
        lblPatientName = new javax.swing.JLabel();
        lblPatientId = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblPrimaryDoctorName = new javax.swing.JLabel();
        txtPatientName = new javax.swing.JTextField();
        txtPatientId = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtPrimaryDoctorName = new javax.swing.JTextField();
        btnCreateVitalSign = new javax.swing.JButton();
        lblPreferredPharmacy = new javax.swing.JLabel();
        txtPreferredPharmacy = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        btnCreatePatient = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblRespiratoryRate = new javax.swing.JLabel();
        lblHeartRate = new javax.swing.JLabel();
        lblSystolicBloodPressure = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        txtSystolicBloodPressure = new javax.swing.JTextField();
        txtRespiratoryRate = new javax.swing.JTextField();
        txtHeartRate = new javax.swing.JTextField();
        txtWeight = new javax.swing.JTextField();
        lblCreate1 = new javax.swing.JLabel();

        lblCreate.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblCreate.setText("Patient Personal Details");

        lblPatientName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblPatientName.setText("Patient Name");

        lblPatientId.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblPatientId.setText("Patient ID");

        lblAge.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblAge.setText("Age");

        lblPrimaryDoctorName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblPrimaryDoctorName.setText("Primary Doctor Name");

        txtPatientName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtPatientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientNameActionPerformed(evt);
            }
        });

        txtPatientId.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        txtAge.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        txtPrimaryDoctorName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        btnCreateVitalSign.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnCreateVitalSign.setText("Create VitalSign");
        btnCreateVitalSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateVitalSignActionPerformed(evt);
            }
        });

        lblPreferredPharmacy.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblPreferredPharmacy.setText("Preferred Pharmacy");

        txtPreferredPharmacy.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        lblGender.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblGender.setText("Gender");

        btnCreatePatient.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnCreatePatient.setText("Resgister Patient");
        btnCreatePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePatientActionPerformed(evt);
            }
        });

        lblRespiratoryRate.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblRespiratoryRate.setText("Respiratory Rate");

        lblHeartRate.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblHeartRate.setText("Heart Rate");

        lblSystolicBloodPressure.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblSystolicBloodPressure.setText("Systolic Blood Pressure");

        lblWeight.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblWeight.setText("Weight (in Pounds)");

        txtSystolicBloodPressure.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        txtRespiratoryRate.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        txtHeartRate.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        txtWeight.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        lblCreate1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblCreate1.setText("Vital Sign Information");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHeartRate)
                                    .addComponent(lblRespiratoryRate))
                                .addGap(88, 88, 88)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtHeartRate)
                                    .addComponent(txtRespiratoryRate, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblWeight)
                                    .addComponent(lblSystolicBloodPressure))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSystolicBloodPressure)
                                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(227, 227, 227)
                                .addComponent(btnCreateVitalSign))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPatientName)
                                    .addComponent(lblPreferredPharmacy)
                                    .addComponent(lblPatientId))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPatientId, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(txtPreferredPharmacy)
                                    .addComponent(txtPatientName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblGender)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblPrimaryDoctorName)
                                            .addComponent(lblAge))
                                        .addGap(21, 21, 21)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPrimaryDoctorName, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(59, 59, 59))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(lblCreate))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(btnCreatePatient))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(lblCreate1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblCreate)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPatientName)
                            .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPatientId)
                            .addComponent(txtPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPreferredPharmacy)
                            .addComponent(txtPreferredPharmacy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAge)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrimaryDoctorName)
                            .addComponent(txtPrimaryDoctorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGender)))
                .addGap(18, 18, 18)
                .addComponent(btnCreatePatient)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCreate1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRespiratoryRate)
                    .addComponent(txtRespiratoryRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWeight)
                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHeartRate)
                    .addComponent(txtHeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSystolicBloodPressure)
                    .addComponent(txtSystolicBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnCreateVitalSign)
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPatientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientNameActionPerformed

    private void btnCreateVitalSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateVitalSignActionPerformed
        
        String tStamp = String.valueOf(new Timestamp(System.currentTimeMillis()));
        float respiRate = Float.valueOf(txtRespiratoryRate.getText());
        float hrtRate = Float.valueOf(txtHeartRate.getText());
        float sysBP = Float.valueOf(txtSystolicBloodPressure.getText());
        float wt = Float.valueOf(txtWeight.getText());
        int age = Integer.valueOf(txtAge.getText());
        
        VitalSign vitalSign = patient.addVitalSign();
        
        if(age>=1 && age<=3){
            if((respiRate>=20 && respiRate<=30) && (hrtRate>=80 && hrtRate<=130) &&
               (sysBP>=80 && sysBP<=110) && (wt>=22 && wt<=31)){
                JOptionPane.showMessageDialog(null, "Inside Toddler");
                vitalSign.setState("NORMAL");
            }
            else {vitalSign.setState("ABNORMAL");}
        }
        else if(age>=4 && age<=5){
            if((respiRate>=20 && respiRate<=30) && (hrtRate>=80 && hrtRate<=120) &&
               (sysBP>=80 && sysBP<=110) && (wt>=31 && wt<=40)){
                JOptionPane.showMessageDialog(null, "Inside Preschooler");
                vitalSign.setState("NORMAL");
            }
            else {vitalSign.setState("ABNORMAL");}
        }
        else if(age>=6 && age<=12){
            if((respiRate>=20 && respiRate<=30) && (hrtRate>=70 && hrtRate<=110) &&
               (sysBP>=80 && sysBP<=120) && (wt>=41 && wt<=92)){
                JOptionPane.showMessageDialog(null, "Inside School Age");
                vitalSign.setState("NORMAL");
            }
            else {vitalSign.setState("ABNORMAL");}
        }
        else if(age>=13){
            if((respiRate>=12 && respiRate<=20) && (hrtRate>=55 && hrtRate<=105) &&
               (sysBP>=110 && sysBP<=120) && (wt>=110)){
                JOptionPane.showMessageDialog(null, "Inside Adolescent");
                vitalSign.setState("NORMAL");
            }
            else {vitalSign.setState("ABNORMAL");}
        }
        
        vitalSign.setRespiratoryRate(respiRate);
        vitalSign.setHeartRate(hrtRate);
        vitalSign.setSystolicBloodPressure(sysBP);
        vitalSign.setWeight(wt);
        vitalSign.setTimestamp(tStamp);
        
        int dialogButton= JOptionPane.YES_NO_OPTION;
        int dialogResult= JOptionPane.showConfirmDialog(null, "VitalSign Created Successfully! Do you want to create more?", "Question", dialogButton);
          
        if (dialogResult==JOptionPane.YES_OPTION){resetFields();}
        //else {}
                  
       
    }//GEN-LAST:event_btnCreateVitalSignActionPerformed

    private void btnCreatePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePatientActionPerformed
        // TODO add your handling code here:
        
        patient.setPatientName(txtPatientName.getText());
        patient.setPatientId(txtPatientId.getText());
        patient.setAge(Integer.valueOf(txtAge.getText()));
        patient.setPrimaryDocName(txtPrimaryDoctorName.getText());
        patient.setPreferredPharmacy(txtPreferredPharmacy.getText());
        
        JOptionPane.showMessageDialog(null, "Patient Details logged into the system!");
        
        txtPatientName.setEnabled(false);
        txtPatientId.setEnabled(false);
        txtAge.setEnabled(false);
        txtPrimaryDoctorName.setEnabled(false);
        txtPreferredPharmacy.setEnabled(false);
        btnCreatePatient.setEnabled(false);
        
        
        txtHeartRate.setEnabled(true);
        txtSystolicBloodPressure.setEnabled(true);
        txtRespiratoryRate.setEnabled(true);
        txtWeight.setEnabled(true);
        btnCreateVitalSign.setEnabled(true);
        
        
    }//GEN-LAST:event_btnCreatePatientActionPerformed


    public void resetFields(){
        txtHeartRate.setText("");
        txtSystolicBloodPressure.setText("");
        txtRespiratoryRate.setText("");
        txtWeight.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreatePatient;
    private javax.swing.JButton btnCreateVitalSign;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCreate;
    private javax.swing.JLabel lblCreate1;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblHeartRate;
    private javax.swing.JLabel lblPatientId;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblPreferredPharmacy;
    private javax.swing.JLabel lblPrimaryDoctorName;
    private javax.swing.JLabel lblRespiratoryRate;
    private javax.swing.JLabel lblSystolicBloodPressure;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtHeartRate;
    private javax.swing.JTextField txtPatientId;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtPreferredPharmacy;
    private javax.swing.JTextField txtPrimaryDoctorName;
    private javax.swing.JTextField txtRespiratoryRate;
    private javax.swing.JTextField txtSystolicBloodPressure;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
