package UserInterface;

import Business.CVSAdministrator;
import Business.Drug;
import Business.Manufacturer;
import Business.ManufacturerDirectory;
import Business.Store;
import Business.StoreDirectory;
import UserInterface.AdminstrativeRole.AdminWorkAreaJPanel;
import UserInterface.StoreAdminRole.StoreAdminWorkAreaJPanel;
import UserInterface.ManufacturerRole.LoginManufacturer;
import UserInterface.StoreAdminRole.LoginStores;
import java.awt.CardLayout;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jdom2.Document;
import org.jdom2.Element;
import org.jdom2.JDOMException;
import org.jdom2.input.SAXBuilder;

/**
 *
 * @author Mihir Mehta / Hechen Gao
 */
public class MainJFrame extends javax.swing.JFrame {
    
    /** Creates new form MainJFrame */
    
    private CVSAdministrator cVSAdministrator;
    private ManufacturerDirectory manufacturerDirectory;
    private StoreDirectory storeDirectory;
    
    public MainJFrame() throws IOException {
        try {
            initComponents();
            //supplierDirectory = new ManufacturerDirectory();
            cVSAdministrator = new CVSAdministrator();
            manufacturerDirectory  = cVSAdministrator.getManufacturerDirectory();
            storeDirectory = cVSAdministrator.getStoreDirectory();
            loadManufacturerFromXML();
            //       masterOrderCatalog = cVSAdministrator.getMasterOrderCatalog();
            setSize(1320, 850);
        } catch (JDOMException ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void loadManufacturerFromXML() throws JDOMException, IOException{
          SAXBuilder builder = new SAXBuilder();
	  File manufacturerXMLFile = new File("C:\\Users\\Ankit Bhayani\\Documents\\NetBeansProjects\\AEDFALL2015Assignment4\\data\\Manufacturer.xml");
          File drugCatalogXMLFile = new File("C:\\Users\\Ankit Bhayani\\Documents\\NetBeansProjects\\AEDFALL2015Assignment4\\data\\Drugs.xml");
          Document doc = (Document) builder.build(drugCatalogXMLFile);
          Element drootnode = doc.getRootElement();          
          

          
          Document d1 = (Document) builder.build(manufacturerXMLFile);
          Element mrootNode = d1.getRootElement();
	  List list1 = mrootNode.getChildren("Manufacturer");

		for (int i = 0; i < list1.size(); i++) {
                    Element node = (Element) list1.get(i);
                    Manufacturer manufacturer = manufacturerDirectory.addManufacturer();
                    manufacturer.setManufactrerName(node.getChildText("name"));

                    List list = drootnode.getChildren(manufacturer.getManufactrerName());
                    for (int j = 0; j < list.size(); j++) {          
                        Element nodes = (Element) list.get(j);

                        Drug drug = manufacturer.getManufacturerDrugCatalog().addDrug();
                        drug.setDrugName(nodes.getChildText("name"));
                        drug.setDrugPrice(Integer.parseInt(nodes.getChildText("price")));
                        drug.setAvail(Integer.parseInt(nodes.getChildText("quantity")));
                        drug.setExpiryDate(nodes.getChildText("expirydate"));
                        drug.setManufacturerName(manufacturer.getManufactrerName());

                    }

                }   

	  File storeXMLFile = new File("C:\\Users\\Ankit Bhayani\\Documents\\NetBeansProjects\\AEDFALL2015Assignment4\\data\\StoreList.xml");
          
          Document d2 = (Document) builder.build(storeXMLFile);
          Element srootNode = d2.getRootElement();
	  List list2 = srootNode.getChildren("Store");

		for (int i = 0; i < list2.size(); i++) {
                    Element node = (Element) list2.get(i);
                    //Manufacturer manufacturer = manufacturerDirectory.addManufacturer();
                    //manufacturer.setManufactrerName(node.getChildText("name"));
                    Store store = cVSAdministrator.storeDirectory.addStore();
                    store.setStoreName(node.getChildText("name"));
                    store.setStoreLocation(node.getChildText("location"));
                  
                }   

    }
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnCVSAdmin = new javax.swing.JButton();
        btnManufacturerManager = new javax.swing.JButton();
        btnStoreAdmin = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(150);

        jPanel1.setBackground(new java.awt.Color(245, 233, 233));

        btnCVSAdmin.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnCVSAdmin.setText("CVS Administrator");
        btnCVSAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCVSAdminActionPerformed(evt);
            }
        });

        btnManufacturerManager.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnManufacturerManager.setText("Manufacturer Role");
        btnManufacturerManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManufacturerManagerActionPerformed(evt);
            }
        });

        btnStoreAdmin.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnStoreAdmin.setText("Store Admin");
        btnStoreAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStoreAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnManufacturerManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCVSAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStoreAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(btnCVSAdmin)
                .addGap(18, 18, 18)
                .addComponent(btnManufacturerManager)
                .addGap(22, 22, 22)
                .addComponent(btnStoreAdmin)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        userProcessContainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(userProcessContainer);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCVSAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCVSAdminActionPerformed

        AdminWorkAreaJPanel awajp = new AdminWorkAreaJPanel(userProcessContainer, cVSAdministrator);
        userProcessContainer.add("AdminWorkAreaJPanel",awajp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnCVSAdminActionPerformed

    private void btnManufacturerManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManufacturerManagerActionPerformed

        LoginManufacturer ls = new LoginManufacturer(userProcessContainer, manufacturerDirectory);
        userProcessContainer.add("LoginSupplierJPanel", ls);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManufacturerManagerActionPerformed

    private void btnStoreAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStoreAdminActionPerformed
        //CustomerWorkAreaJPanel customerWorkAreaJPanel = new StoreAdminWorkAreaJPanel(userProcessContainer,cVSAdministrator);
        LoginStores loginStores = new LoginStores(userProcessContainer,cVSAdministrator);
        userProcessContainer.add("LoginStores",loginStores);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnStoreAdminActionPerformed

  

    
    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainJFrame().setVisible(true);
                    //loadManufacturerFromXML();
                } catch (IOException ex) {
                    Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCVSAdmin;
    private javax.swing.JButton btnManufacturerManager;
    private javax.swing.JButton btnStoreAdmin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables

}
