/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ManufacturerRole;


import userinterface.PatientRole.*;
import Business.Drug.Drug;
import Business.EcoSystem;
import Business.Enterprise.DrugAdministrationEnterprise;
import Business.Enterprise.DrugManufacturerEnterprise;
import Business.Enterprise.Enterprise;
import Business.IndividualUser.Doctor;
import Business.IndividualUser.Manufacturer;
import Business.IndividualUser.Patient;
import Business.Network.Network;
import Business.Orders.Order;
import Business.Orders.OrderItem;
import Business.Organization.DoctorOrganization;
import Business.Organization.ManufacturerOrganization;
import Business.Organization.Organization;
import Business.Organization.PatientOrganization;
import Business.UserAccount.UserAccount;
import Business.VitalSigns.VitalSign;
import Business.WorkQueue.GetDiagnosisWorkRequest;
import Business.WorkQueue.InspectionRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ankit Bhayani
 */
public class DrugFeedbackJPanel extends javax.swing.JPanel {

    
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Patient patient;
    private Doctor doc;
    private ManufacturerOrganization manufacturerOrganization;
    private Enterprise enterprise;
    private DrugManufacturerEnterprise dme;
    private EcoSystem ecoSystem;
    private VitalSign vs;
    private DoctorOrganization doctorOrganization;
    private UserAccount docUA =null; 
    private Drug selectedDrug;
    private InspectionRequest req;
    /**
     * Creates new form CreateUserAccountJPanel
     */
    public DrugFeedbackJPanel(JPanel pnl, UserAccount ua, Organization o, Enterprise e, EcoSystem es) {
        initComponents();
        this.userProcessContainer = pnl;
        this.userAccount = ua;
        this.manufacturerOrganization = (ManufacturerOrganization)o;
        this.enterprise = e;
        this.ecoSystem = es;
        this.dme=(DrugManufacturerEnterprise)enterprise;
        //this.patient= (Patient)ua.getEmployee();
        populateDrug();
        populateRequestTable();
        cmbTestResult.setEnabled(false);
        btnRequestTest.setEnabled(false);
        //deleteWorkRequests();
        
    }
    
    public void deleteWorkRequests(){
        
        int l =userAccount.getWorkQueue().getWorkRequestList().size();
            while(l!=0) {
                userAccount.getWorkQueue().getWorkRequestList().remove(l-1);
                l--;
            }
            JOptionPane.showMessageDialog(null, userAccount.getWorkQueue().getWorkRequestList());
            
    }
    
    
        
    public void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel)workRequestJTable.getModel();
        
        model.setRowCount(0);
        
        for(WorkRequest request : dme.getWorkQueue().getWorkRequestList()){
            if(request instanceof InspectionRequest){
                Object[] row = new Object[7];
                row[0] = request;
                row[1] = ((InspectionRequest)request).getDrug();
                row[2] = request.getRequestDate();
                row[3] = ((InspectionRequest)request).getPatient();
                row[4] = ((InspectionRequest)request).getProblemExperienced();
                row[5] = request.getStatus();
                String result = ((InspectionRequest) request).getTestResult();
                row[6] = result == null ? "Waiting" : result;
                
                //row[4] = request.getStatus();
                model.addRow(row);
            }
        }
    }
    
    

    public void populateDrug(){
        
        //Drug d[] = new Drug[100];
        
        /*cmbDrugName.removeAllItems();
        //cmbDrugName.addItem("Please select a Drug");
        for(Order o: patient.getPatientDrugOrders().getOrders()){
            for(OrderItem oi : o.getOrderItems()){
                //JOptionPane.showMessageDialog(null, "Storing Values "+ oi.getDrug());
                //d[i]=oi.getDrug();
                cmbDrugName.addItem(oi.getDrug());
                //JOptionPane.showMessageDialog(null, "Manufacturer Name "+ oi.getDrug().getManufacturerName());
            }
        }
        
        */
        //cmbDrugName.addItem(oi.getDrug());
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        btnBackUA = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtProblemExperience = new javax.swing.JTextArea();
        btnRequestTest = new javax.swing.JButton();
        txtDrugName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDrugExpiryDate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbTestResult = new javax.swing.JComboBox();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 24)); // NOI18N
        jLabel4.setText("Monitor Drug Feeback");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        btnBackUA.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnBackUA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/PatientRole/backButton.png"))); // NOI18N
        btnBackUA.setText("Back");
        btnBackUA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackUAActionPerformed(evt);
            }
        });
        add(btnBackUA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Inspection Requests", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14), new java.awt.Color(0, 153, 0))); // NOI18N

        workRequestJTable.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Message", "Drug", "Request Time", "Sender", "Problems", "Status", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        workRequestJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                workRequestJTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(workRequestJTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 910, 230));

        txtProblemExperience.setColumns(20);
        txtProblemExperience.setRows(5);
        jScrollPane1.setViewportView(txtProblemExperience);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 300, 90));

        btnRequestTest.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnRequestTest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/PatientRole/feedBackButton.png"))); // NOI18N
        btnRequestTest.setText("Send Input to Drug Controller");
        btnRequestTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestTestActionPerformed(evt);
            }
        });
        add(btnRequestTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, -1, -1));

        txtDrugName.setEditable(false);
        txtDrugName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        add(txtDrugName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 300, 20));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("Addition Test Results");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, 120, 20));

        txtDrugExpiryDate.setEditable(false);
        txtDrugExpiryDate.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        add(txtDrugExpiryDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, 250, 20));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Drug Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, 20));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setText("Problems/Experience");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, 20));

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setText("Drug Expiry Date");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 140, 20));

        cmbTestResult.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cmbTestResult.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Test Result looks good, no issue", "Need more time to resolve the issue", "Bad Result Drug needs Modification" }));
        add(cmbTestResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 250, -1));
    }// </editor-fold>//GEN-END:initComponents

    

    
    private void btnBackUAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackUAActionPerformed
        //muajp.refreshTable();
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_btnBackUAActionPerformed

    private void workRequestJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workRequestJTableMouseClicked

        int selectedRow = workRequestJTable.getSelectedRow();
        req = (InspectionRequest) workRequestJTable.getValueAt(selectedRow, 0);

        txtDrugName.setText(req.getDrug().getDrugName());
        txtDrugExpiryDate.setText(req.getDrug().getExpiryDate());

        txtProblemExperience.setText(req.getProblemExperienced());

        if(req.getStatus().equalsIgnoreCase("FDA requested further test")){
            btnRequestTest.setEnabled(true);
            cmbTestResult.setEnabled(true);
        }


    }//GEN-LAST:event_workRequestJTableMouseClicked

    private void btnRequestTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestTestActionPerformed

        req.setStatus(cmbTestResult.getSelectedItem().toString());
        populateRequestTable();
        btnRequestTest.setEnabled(false);
    }//GEN-LAST:event_btnRequestTestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackUA;
    private javax.swing.JButton btnRequestTest;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbTestResult;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtDrugExpiryDate;
    private javax.swing.JTextField txtDrugName;
    private javax.swing.JTextArea txtProblemExperience;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
