/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SalesPerson;

import Business.Logic.Business;
import Business.Logic.Customer;
import Business.Logic.SalesPerson;
import Business.Logic.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Ankit Bhayani
 */
public class EmployeeWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Business business;
    private UserAccount ua;
    //private SalesPerson employee;
    
    /**
     * Creates new form EmployeeWorkAreaJPanel
     */
    public EmployeeWorkAreaJPanel(JPanel userProcessContainer,Business business,UserAccount ua) {
        initComponents();
        this.business=business;
        this.userProcessContainer=userProcessContainer;
        this.ua=ua;
        SalesPerson employee = (SalesPerson)ua.getPerson();
        lblSalesPersonName.setText(employee.getFirstName().concat(" " +employee.getLastName()));
        lblActivity.setText("Manage Customers");
        populateCustomerComboBox();
        
    }

    public void populateCustomerComboBox(){
        cmbCustomerName.removeAllItems();
        
        for(Customer customer: business.getCustomerDirectory().getCustomerList()){
            cmbCustomerName.addItem(customer);
        }

    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSalesPersonName = new javax.swing.JLabel();
        lblActivity = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnServeCustomer = new javax.swing.JButton();
        btnReviewSalesOrder = new javax.swing.JButton();
        cmbCustomerName = new javax.swing.JComboBox();
        lblActivity1 = new javax.swing.JLabel();
        lblActivity2 = new javax.swing.JLabel();
        btnAddCustomer = new javax.swing.JButton();
        lblActivity3 = new javax.swing.JLabel();
        lblActivity4 = new javax.swing.JLabel();

        lblSalesPersonName.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        lblSalesPersonName.setForeground(new java.awt.Color(0, 0, 255));
        lblSalesPersonName.setText("SalesPerson Name");

        lblActivity.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        lblActivity.setForeground(new java.awt.Color(255, 0, 0));
        lblActivity.setText("Activity");

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel4.setText("Xerox Sales Employee Work Area");

        jSeparator1.setPreferredSize(new java.awt.Dimension(80, 10));

        btnServeCustomer.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnServeCustomer.setText("Serve Customer");
        btnServeCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServeCustomerActionPerformed(evt);
            }
        });

        btnReviewSalesOrder.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnReviewSalesOrder.setText("Review Sales Order History");
        btnReviewSalesOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReviewSalesOrderActionPerformed(evt);
            }
        });

        cmbCustomerName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cmbCustomerName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblActivity1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblActivity1.setText("Sales Person Name:");

        lblActivity2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblActivity2.setText("Customer's List: ");

        btnAddCustomer.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnAddCustomer.setText("Add Customer");
        btnAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustomerActionPerformed(evt);
            }
        });

        lblActivity3.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblActivity3.setText("Other Operations:");

        lblActivity4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblActivity4.setText("Activity: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblActivity1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblSalesPersonName)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblActivity4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblActivity))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(btnAddCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnReviewSalesOrder))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(142, 142, 142)
                                                .addComponent(lblActivity3))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblActivity2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cmbCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnServeCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(50, 50, 50)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSalesPersonName)
                    .addComponent(lblActivity)
                    .addComponent(lblActivity1)
                    .addComponent(lblActivity4))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblActivity2)
                    .addComponent(btnServeCustomer))
                .addGap(69, 69, 69)
                .addComponent(lblActivity3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReviewSalesOrder)
                    .addComponent(btnAddCustomer))
                .addContainerGap(199, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustomerActionPerformed
        
        AddCustomer addCustomer = new AddCustomer(userProcessContainer, business);
        userProcessContainer.add("AddCustomer",addCustomer);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAddCustomerActionPerformed

    private void btnServeCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServeCustomerActionPerformed
        
        Customer c = (Customer)cmbCustomerName.getSelectedItem();
        if(c!=null){
            ServeCustomer serveCustomer = new ServeCustomer(userProcessContainer, business,ua,c);
            userProcessContainer.add("ServeCustomer",serveCustomer);
            CardLayout layout = (CardLayout)userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        else{JOptionPane.showMessageDialog(null, "Please select a store!!");}
		
    }//GEN-LAST:event_btnServeCustomerActionPerformed

    private void btnReviewSalesOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReviewSalesOrderActionPerformed
        ReviewSalesOrder rso = new ReviewSalesOrder(userProcessContainer, business,ua);
        userProcessContainer.add("ReviewSalesOrder",rso);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
					
        
    }//GEN-LAST:event_btnReviewSalesOrderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCustomer;
    private javax.swing.JButton btnReviewSalesOrder;
    private javax.swing.JButton btnServeCustomer;
    private javax.swing.JComboBox cmbCustomerName;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblActivity;
    private javax.swing.JLabel lblActivity1;
    private javax.swing.JLabel lblActivity2;
    private javax.swing.JLabel lblActivity3;
    private javax.swing.JLabel lblActivity4;
    private javax.swing.JLabel lblSalesPersonName;
    // End of variables declaration//GEN-END:variables
}
