/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PharmaManagerRole;

import userinterface.StoreAdminRole.*;
import userinterface.DoctorRole.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;
import Business.Organization.PharmaManagerOrganization;
import Business.Organization.StorePharmacistOrganization;
import Business.UserAccount.UserAccount;
import UserInterface.DoctorRole.DoctorMedicalAdviceJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Ankit Bhayani
 */
public class PharmacistManagerWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private PharmaManagerOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem ecoSystem;
    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public PharmacistManagerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, PharmaManagerOrganization organization, Enterprise enterprise, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.ecoSystem= ecoSystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageInventory = new javax.swing.JButton();
        btnProcessRequests = new javax.swing.JButton();

        btnManageInventory.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        btnManageInventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Images/1449760285_Global_manager.png"))); // NOI18N
        btnManageInventory.setText("Manage Enterprise Drugs");
        btnManageInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageInventoryActionPerformed(evt);
            }
        });

        btnProcessRequests.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        btnProcessRequests.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Images/1449761030_git-pull-request.png"))); // NOI18N
        btnProcessRequests.setText("Assign Incoming Requests");
        btnProcessRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessRequestsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnProcessRequests, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageInventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(btnManageInventory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProcessRequests)
                .addContainerGap(152, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageInventoryActionPerformed
        ManageEnterPriseDrugJPanel ms = new ManageEnterPriseDrugJPanel(userProcessContainer, userAccount,organization,enterprise,ecoSystem);
        userProcessContainer.add("ManageSupplierAdministrative", ms);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageInventoryActionPerformed

    private void btnProcessRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessRequestsActionPerformed
        
        DrugLookUpStoreAssignJPanel pharmaManagerWorkAreaJPanel = new DrugLookUpStoreAssignJPanel(userProcessContainer, userAccount, organization,enterprise,ecoSystem );
        userProcessContainer.add("PharmaManagerWorkAreaJPanel",pharmaManagerWorkAreaJPanel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnProcessRequestsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageInventory;
    private javax.swing.JButton btnProcessRequests;
    // End of variables declaration//GEN-END:variables
}
