/*
 * BrowseDrugs.java
 *
 * Created on October 10, 2008, 9:10 AM
 */
package userinterface.StoreAdminRole;


import Business.Drug.Drug;
import Business.EcoSystem;
import Business.Enterprise.DrugManufacturerEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PharmacyEnterprise;
import Business.IndividualUser.Doctor;
import Business.IndividualUser.PharmaManager;
import Business.IndividualUser.StorePharmacist;
import Business.Organization.PharmaManagerOrganization;
import Business.Organization.StorePharmacistOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AppointmentWorkRequest;
import com.oracle.jrockit.jfr.Producer;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Rushabh
 */
public class ManageInventoryStoreJPanel extends javax.swing.JPanel {
    
    
    private boolean isCheckedOut = false;
    private JPanel userProcessContainer;
    private StorePharmacistOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private AppointmentWorkRequest appointmentWorkRequest;
    private String appointmentTimeRequested;
    private Doctor doctor;
    private EcoSystem ecoSystem;
    private PharmaManager pharmacist;
    private DrugManufacturerEnterprise drugManufacturerEnterprise;
    private PharmacyEnterprise pharmacyEnterprise;
    private StorePharmacist storePharmacist;
    
    /** Creates new form BrowseProducts */
    public ManageInventoryStoreJPanel(JPanel userProcessContainer, UserAccount account, StorePharmacistOrganization organization, Enterprise enterprise, EcoSystem ecoSystem) {
        initComponents();
        //        this.cVSAdministrator=business;
        //        this.store=store;
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.storePharmacist = (StorePharmacist)account.getEmployee();
        this.ecoSystem = ecoSystem;
        
        if(ecoSystem.getNewsAboutDrug()!=null)
            lblEcosystemDrugNews.setText(ecoSystem.getNewsAboutDrug());
        //this.pharmacist=(PharmaManager)userAccount.getEmployee();
        this.pharmacyEnterprise = (PharmacyEnterprise)enterprise;
        //        txtName.setText(store.getStoreName());
        populateDrugInventoryTable();
        refershStoreTable();
    }
    


    public void populateDrugInventoryTable(){
 
        
        int rowCount = CVSDrugCatalogTable.getRowCount();
        DefaultTableModel dtm = (DefaultTableModel)CVSDrugCatalogTable.getModel();
        
        for(int i=rowCount-1; i>=0;i--){
                dtm.removeRow(i);
        }
        
        for(Drug d: pharmacyEnterprise.getPharmaDrugCatalog().getDrugList()){
                Object row[] = new Object[5];
                row[0]=d;
                row[1]=d.getDrugPrice();
                row[2]=d.getCount();
                row[3]=d.getExpiryDate();
                row[4]=d.getManufacturerName();
                dtm.addRow(row);
        }

    }
    
    
    public void refreshTableForSearch(String prodName){
   /*     int rowCount = productTable.getRowCount();
        DefaultTableModel dtm = (DefaultTableModel)productTable.getModel();
        for(int i=rowCount-1; i>=0;i--){
            dtm.removeRow(i);
        }
        
        for(Manufacturer supplier: manufacturerDirectory.getManufacturerlist()){
            for(Drug drug: supplier.getProductCatalog().getProductcatalog()){
                if(drug.getProdName().equals(prodName)){
                    Object row[] = new Object[4];
                    row[0]=drug;
                    row[1]=drug.getModelNumber();
                    row[2]=drug.getPrice();
                    row[3]=drug.getAvail();
                    dtm.addRow(row);
                }
            }
        }*/
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        CVSDrugCatalogTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addInStore = new javax.swing.JButton();
        quantitySpinner = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        StoreTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        lblEcosystemDrugNews = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(750, 511));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CVSDrugCatalogTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CVSDrugCatalogTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Drug Name", "Drug Price", "Availability", "Expiry Date", "Manufacturer"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(CVSDrugCatalogTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 590, 100));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Store");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 110, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Store Catalog");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 110, -1));

        addInStore.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        addInStore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Images/1449760826_add.png"))); // NOI18N
        addInStore.setText("Add in Store");
        addInStore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addInStoreActionPerformed(evt);
            }
        });
        add(addInStore, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, -1, -1));

        quantitySpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        add(quantitySpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 50, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Quantity:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, -1, -1));

        StoreTable.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        StoreTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Item Name", "Price", "Stock", "IsBelowThreshold", "Manufacturer"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(StoreTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 580, 110));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Enterprise Master Drug Catalog");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 250, -1));

        txtName.setEditable(false);
        txtName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(102, 102, 102), null, null));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 150, -1));

        backJButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/PatientRole/backButton.png"))); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));

        lblEcosystemDrugNews.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        lblEcosystemDrugNews.setForeground(new java.awt.Color(255, 0, 0));
        add(lblEcosystemDrugNews, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addInStoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addInStoreActionPerformed
      
        
        int selectedRow = CVSDrugCatalogTable.getSelectedRow();
        Drug selectedDrug;
        //Manufacturer selectedManufacturer;
        //int salesPrice=0;

        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select a row!");
            return;
        }
        else{
            selectedDrug=(Drug)CVSDrugCatalogTable.getValueAt(selectedRow, 0);
            //selectedManufacturer=cVSAdministrator.manufacturerDirectory.searchManufacturer(selectedDrug.getManufacturerName());
        }

        int fetchQty = (Integer)quantitySpinner.getValue();
        if(fetchQty<=0){
            JOptionPane.showMessageDialog(null, "Quantity cant be negative or 0");
        }
        else if (fetchQty>selectedDrug.getCount()){
            JOptionPane.showMessageDialog(null, "No sufficient drugs availale this time");
        }
        else if(fetchQty<=selectedDrug.getCount()){
            boolean alreadyPresent= false;
            //JOptionPane.showMessageDialog(null, store.storeDrugCatalog.getDrugList().size());
            
           for(Drug d: storePharmacist.storeDrugCatalog.drugList){
                if(d.getDrugName().equals(selectedDrug.getDrugName())){
                    //JOptionPane.showMessageDialog(null, "Same Drug adding again");
                    alreadyPresent= true;
                    if(d.isBelowThreshold()){
                        int oldCount = selectedDrug.getCount();
                        int newCount = oldCount - fetchQty;
                        selectedDrug.setCount(newCount);
                        d.setStock(fetchQty+d.getStock());

                        if(d.getStock()>10)
                        d.setBelowThreshold(false);

                        populateDrugInventoryTable();
                        refershStoreTable();
                        break;
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Already in sufficient stock");
                    }
                }
            }

            if(!alreadyPresent){
                
                //JOptionPane.showMessageDialog(null, "new Drug");
                int oldCount = selectedDrug.getCount();
                int newCount = oldCount - fetchQty;
                selectedDrug.setCount(newCount);
                selectedDrug.setStock(fetchQty);
          
                Drug drug = storePharmacist.storeDrugCatalog.addDrug();
                drug.setDrugName(selectedDrug.getDrugName());
                drug.setDrugPrice(selectedDrug.getDrugPrice());
                drug.setStock(selectedDrug.getStock());
                drug.setManufacturerName(selectedDrug.getManufacturerName());
                drug.setExpiryDate(selectedDrug.getExpiryDate());
                //JOptionPane.showMessageDialog(null, store.storeDrugCatalog.getDrugList().size());
                populateDrugInventoryTable();
                refershStoreTable();
            }

        }
        else{
            JOptionPane.showMessageDialog(null, "Quantity requested is not available");
        }

          
    }//GEN-LAST:event_addInStoreActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        //Component[] componentArray = userProcessContainer.getComponents();
        //Component component = componentArray[componentArray.length - 1];
        //DoctorMedicalAdviceJPanel dwjp = (DoctorMedicalAdviceJPanel) component;
        //dwjp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void refershStoreTable(){
        
        int rowCount = StoreTable.getRowCount();
        DefaultTableModel dtm = (DefaultTableModel)StoreTable.getModel();
        
        for(int i=rowCount-1; i>=0;i--){
                dtm.removeRow(i);
        }
        
        //JOptionPane.showMessageDialog(null, store.getStoreName());
        
        for(Drug d: storePharmacist.storeDrugCatalog.getDrugList()){
            
            
                if(d.getStock()<10)
                    d.setBelowThreshold(true);
            
                Object row[] = new Object[5];
                row[0]=d;
                row[1]=d.getDrugPrice();
                row[2]=d.getStock();
                row[3]=d.isBelowThreshold();
                row[4]=d.getManufacturerName();
                dtm.addRow(row);
        }

        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CVSDrugCatalogTable;
    private javax.swing.JTable StoreTable;
    private javax.swing.JButton addInStore;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEcosystemDrugNews;
    private javax.swing.JSpinner quantitySpinner;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
