/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.StoreAdminRole;

import userinterface.DoctorRole.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;
import Business.Organization.StorePharmacistOrganization;
import Business.UserAccount.UserAccount;
import UserInterface.DoctorRole.DoctorMedicalAdviceJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.PatientRole.ViewPatientOrders;

/**
 *
 * @author Ankit Bhayani
 */
public class StorePharmacistWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private StorePharmacistOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem ecoSystem;
    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public StorePharmacistWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, StorePharmacistOrganization organization, Enterprise enterprise, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.ecoSystem= ecoSystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageInventory = new javax.swing.JButton();
        btnProcessRequests = new javax.swing.JButton();
        btnCheckOrders = new javax.swing.JButton();

        btnManageInventory.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        btnManageInventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Images/1449760285_Global_manager.png"))); // NOI18N
        btnManageInventory.setText("Manage Store Inventory");
        btnManageInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageInventoryActionPerformed(evt);
            }
        });

        btnProcessRequests.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        btnProcessRequests.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/PatientRole/solutionButton.png"))); // NOI18N
        btnProcessRequests.setText("Process Requests");
        btnProcessRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessRequestsActionPerformed(evt);
            }
        });

        btnCheckOrders.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        btnCheckOrders.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/PatientRole/viewButton.png"))); // NOI18N
        btnCheckOrders.setText("Check Orders");
        btnCheckOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOrdersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnProcessRequests, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageInventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCheckOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(btnManageInventory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProcessRequests)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCheckOrders)
                .addContainerGap(112, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOrdersActionPerformed

        ViewStoreOrders viewStoreOrders = new ViewStoreOrders(userProcessContainer,ecoSystem,userAccount);
        userProcessContainer.add("ViewStoreOrders", viewStoreOrders);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnCheckOrdersActionPerformed

    private void btnManageInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageInventoryActionPerformed
        
        ManageInventoryStoreJPanel storeAdminWorkAreaJPanel = new ManageInventoryStoreJPanel(userProcessContainer, userAccount, organization,enterprise,ecoSystem );
        userProcessContainer.add("StoreAdminWorkAreaJPanel",storeAdminWorkAreaJPanel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageInventoryActionPerformed

    private void btnProcessRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessRequestsActionPerformed
        
        ProcessRequestsStoreJPanel processRequestsStoreJPanel = new ProcessRequestsStoreJPanel(userProcessContainer, userAccount, organization,enterprise,ecoSystem );
        userProcessContainer.add("ProcessRequestsStoreJPanel",processRequestsStoreJPanel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnProcessRequestsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckOrders;
    private javax.swing.JButton btnManageInventory;
    private javax.swing.JButton btnProcessRequests;
    // End of variables declaration//GEN-END:variables
}
